[package]
name = "netlib"
version = "0.1.0"
edition = "2021"
description = ""
authors = [ "minghu6 <a19678zy@163.com>" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = { version = "0.2", features = ["extra_traits"] }
getset = "0.1.2"
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
memmap2 = "0.5.4"
# nix = "0.24.1"
either = "~1.7"
dns-lookup = "1"

crossbeam-channel = "0.5"
signal-hook = "0.3.14"

clap = { version = "^3", features = ["derive"] }
clap_complete = "3.1.1"
shellexpand = "2.1"


[[bin]]
name="tcp_server_test0"
path="bin/tcp_server_test0.rs"

[[bin]]
name = "ping"
path = "bin/ping.rs"

